name: docker-build
on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # refs: https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # refs: https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (backend)
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/backend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/backend:buildcache,mode=max

      - name: Build and push (frontend)
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/frontend:buildcache,mode=max

      - name: Build and push (nginx)
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/nginx:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/nginx:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/nginx:buildcache,mode=max

      - name: Build and push (devcontainer)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .devcontainer/Dockerfile
          build-args: |
            PYTHON_VERSION=3.9
            NODE_VERSION=14
          push: true
          tags: ghcr.io/${{ github.repository }}/devcontainer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
